# Generated by Django 5.2.1 on 2025-07-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Изображение')),
                ('on_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('count_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['title'],
            },
        ),
    ]
